'use client'

import './globals.css';
import { Inter } from 'next/font/google';
import { StoreProvider } from "@/redux/StoreProvider";
import { Header } from '@/components/Header/Header';
import styles from "./page.module.css";
import { Footer } from '@/components/Footer/Footer';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider>
          <Header/>
          <div id="modalRoot"></div>

          <main className={styles.main_container}>
            {children}
          </main>

          <Footer/>
        </StoreProvider>
      </body>
    </html>
  )
}
